import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: [
    "latin",
    "latin-ext",
    "cyrillic",
    "cyrillic-ext",
    "greek",
    "greek-ext",
  ],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Grahok Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased p-6 flex items-start gap-6`}
      >
        <aside className="h-dvh min-h-dvh bg-white w-1/6 min-w-45">
          <nav>
            <ul className="flex flex-col gap-2">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/all-entries">All Entries</a>
              </li>
              <li>
                <a href="/add-entry">Add Entry</a>
              </li>
              <li>
                <a href="/customers/all">All Customers</a>
              </li>
              <li>
                <a href="/customers/add">Add Customer</a>
              </li>
              <li>
                <a href="/products/all">All Products</a>
              </li>
              <li>
                <a href="/products/add">Add Product</a>
              </li>
            </ul>
          </nav>
        </aside>
        {children}
      </body>
    </html>
  );
}
