import { Inter } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({
  subsets: [
    "latin",
    "latin-ext",
    "cyrillic",
    "cyrillic-ext",
    "greek",
    "greek-ext",
  ],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Grahok Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex gap-6 min-h-dvh`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="bg-gray-50 text-gray-800 flex flex-col gap-8 p-6 w-full">
            <h1 className="text-4xl font-bold text-blue-600 text-center">
              Grahok Database
            </h1>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
