name: Trigger Vercel Deploy Hook

on:
  push:
    branches:
      - main  # Or whatever branch you want to trigger on

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
